In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [6]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
x=data[['Age','Fare']]
y=data['Survived']

In [8]:
x

Age     Fare
0    22.000000   7.2500
1    38.000000  71.2833
2    26.000000   7.9250
3    35.000000  53.1000
4    35.000000   8.0500
..         ...      ...
886  27.000000  13.0000
887  19.000000  30.0000
888  29.699118  23.4500
889  26.000000  30.0000
890  32.000000   7.7500

[891 rows x 2 columns]

In [9]:
x['Fare']=x['Fare']*5698981

C:\Users\CHANDU\AppData\Local\Temp\ipykernel_10892\3430883504.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Fare']=x['Fare']*5698981


In [10]:
x

Age          Fare
0    22.000000  4.131761e+07
1    38.000000  4.062422e+08
2    26.000000  4.516442e+07
3    35.000000  3.026159e+08
4    35.000000  4.587680e+07
..         ...           ...
886  27.000000  7.408675e+07
887  19.000000  1.709694e+08
888  29.699118  1.336411e+08
889  26.000000  1.709694e+08
890  32.000000  4.416710e+07

[891 rows x 2 columns]

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
mx=MinMaxScaler()

In [13]:
mx.fit_transform(x)

array([[0.27117366, 0.01415106],
       [0.4722292 , 0.13913574],
       [0.32143755, 0.01546857],
       ...,
       [0.36792055, 0.04577135],
       [0.32143755, 0.0585561 ],
       [0.39683338, 0.01512699]])

In [14]:
x_norm=mx.fit_transform(x)

In [15]:
x_norm_train,x_norm_test=x_norm[:690],x_norm[690:]

In [16]:
x_train,x_test=x[:690],x[690:]
y_train,y_test=y[:690],y[690:]

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lg=LogisticRegression()

In [19]:
lg.fit(x_train,y_train)

LogisticRegression()

In [20]:
lg.score(x_test,y_test)

0.39303482587064675

In [21]:
lg_norm=LogisticRegression()

In [22]:
lg_norm.fit(x_norm_train,y_train)

LogisticRegression()

In [23]:
lg_norm.score(x_norm_test,y_test)

0.6766169154228856

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rd=RandomForestClassifier()

In [26]:
rd.fit(x_train,y_train)

RandomForestClassifier()

In [27]:
rd.score(x_test,y_test)

0.6915422885572139

In [28]:
t=[5,10,15,2,3,18,30]

In [29]:
sum(t)

83

In [30]:
np.array(t)/sum(t)

array([0.06024096, 0.12048193, 0.18072289, 0.02409639, 0.03614458,
       0.21686747, 0.36144578])

In [31]:
data['Fare']/sum(data['Fare'])

0      0.000253
1      0.002484
2      0.000276
3      0.001851
4      0.000281
         ...   
886    0.000453
887    0.001046
888    0.000817
889    0.001046
890    0.000270
Name: Fare, Length: 891, dtype: float64

In [32]:
min1=min(data['Fare'].values)
max1=max(data['Fare'].values)

In [33]:
for i in data['Fare'].values:
    print((i-min1)/(max1-min1))

0.014151057562208049
0.13913573538264068
0.015468569817999833
0.10364429745562033
0.015712553569072387
0.01650950209357577
0.10122885832000206
0.04113566043083236
0.021730754366528396
0.058694292654020104
0.03259622914329302
0.051822148727810165
0.015712553569072387
0.06104473451835265
0.015330377421392339
0.03122992013728673
0.056848213999904744
0.025374310111545468
0.03513366015444757
0.014102260811993537
0.050748620223090936
0.025374310111545468
0.015671954672893913
0.06929138530460492
0.04113566043083236
0.061264319894317944
0.014102260811993537
0.5133418122566505
0.01537917417160685
0.015411575213749284
0.05410739813385612
0.2859895551532101
0.015126992566498259
0.020494635090094415
0.16038672010106
0.10149724044618187
0.014110458666029575
0.015712553569072387
0.03513366015444757
0.021942337075458514
0.018493968331299484
0.04098927018018883
0.015411575213749284
0.08115719346076702
0.01537917417160685
0.015712553569072387
0.030253985132996517
0.015126992566498259
0.0423149802900166

In [34]:
data['Fare']=[(i-min1)/(max1-min1) for i in data['Fare'].values]

In [35]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket      Fare Cabin Embarked  
0        1      0         A/5 21171  0.014151   NaN        S  
1        1      0          PC 17599  0.139136   C85        C  
2        0      0  STON/O2. 3101282  0.015469   NaN        S  
3        1      0            113803  0.103644  C123        S  
4        0      0            373450  0.015713   NaN        S  
..     ...    ...               ...       ...   ...      ...  
886      0      0            211536  0.025374   NaN        S  
887      0      0            112053  0.058556   B42        S  
888      1      2        W./C. 6607  0.045771   NaN        S  
889      0      0            111369  0.058556  C148        C  
890      0      0            370376  0.015127   NaN        Q  

[891 rows x 12 columns]

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sd=StandardScaler()

In [38]:
sd.fit_transform(data[['Age','Fare']])

array([[-0.5924806 , -0.50244517],
       [ 0.63878901,  0.78684529],
       [-0.2846632 , -0.48885426],
       ...,
       [ 0.        , -0.17626324],
       [-0.2846632 , -0.04438104],
       [ 0.17706291, -0.49237783]])

In [39]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket      Fare Cabin Embarked  
0        1      0         A/5 21171  0.014151   NaN        S  
1        1      0          PC 17599  0.139136   C85        C  
2        0      0  STON/O2. 3101282  0.015469   NaN        S  
3        1      0            113803  0.103644  C123        S  
4        0      0            373450  0.015713   NaN        S  
..     ...    ...               ...       ...   ...      ...  
886      0      0            211536  0.025374   NaN        S  
887      0      0            112053  0.058556   B42        S  
888      1      2        W./C. 6607  0.045771   NaN        S  
889      0      0            111369  0.058556  C148        C  
890      0      0            370376  0.015127   NaN        Q  

[891 rows x 12 columns]

In [40]:
x=data[['Age','Fare']]

In [41]:
y=data['Survived']

In [42]:
x_train,x_test=x[:690],x[690:]

In [43]:
x_train

Age      Fare
0    22.0  0.014151
1    38.0  0.139136
2    26.0  0.015469
3    35.0  0.103644
4    35.0  0.015713
..    ...       ...
685  25.0  0.081157
686  14.0  0.077465
687  19.0  0.019852
688  18.0  0.015216
689  15.0  0.412503

[690 rows x 2 columns]

In [44]:
x['Fare']=x['Fare']*56989

C:\Users\CHANDU\AppData\Local\Temp\ipykernel_10892\53308094.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Fare']=x['Fare']*56989


In [45]:
y=data['Survived']

In [46]:
y_train,y_test=y[:690],y[690:]

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
lg=LogisticRegression()

In [49]:
lg.fit(x_train,y_train)

LogisticRegression()

In [50]:
lg.score(x_test,y_test)

0.6716417910447762

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rd=RandomForestClassifier()

In [53]:
rd.fit(x_train,y_train)

RandomForestClassifier()

In [54]:
rd.score(x_test,y_test)

0.6915422885572139

In [55]:
x_std=sd.fit_transform(x[['Age','Fare']])

In [56]:
x_std_train,x_std_test=x_std[:690],x_std[690:]

In [57]:
lg_std=LogisticRegression()

In [58]:
lg_std.fit(x_std_train,y_train)

LogisticRegression()

In [59]:
lg_std.score(x_std_test,y_test)

0.6766169154228856